### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by tessmanned** [nhjjreuter/cbptools#1]
Hello,

I hope this message finds you well. I am currently considering using cbptools and wanted to ensure that my development environment meets the necessary requirements for compatibility.

Could you please clarify the version(s) of Python required to run this? I've tried 3.7.12 and newer versions, but that didn't work...

Additionally, if there are any other version-specific dependencies or considerations I should be aware of, I would greatly appreciate your insights on those as well.

Thank you for your time and effort. Looking forward to your response!

Best regards,
Edgar

**Comment by nhjjr** [comment]
Hey Edgar,

Sorry for the late reply. cbptools was written quite some time ago using Python 3.5 and older versions of dependencies. Because it's very cumbersome to get things to work with such an old version of Python, I'm currently working on an update to use Python 3.12 and the latest versions of all the dependencies.
